name: A GitHub workflow yaml file for cherry picking
description: Cherry picks commit to a given branch
inputs:
  release:
    description: release branch to cherry pick to
    required: true
  email:
    description: email for cherry picking
    required: true
  name:
    description: user name for cherry picking
    required: true
outputs:
  success:
    description: whether cherry pick is successful
    value: ${{ steps.cherrypick.outputs.success }}
runs:
  using: "composite"
  steps:
    - id: cherrypick
      run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.release }} ${{ inputs.email }} ${{ inputs.name }}
      shell: bash