name: PR for release branch
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - id: cherrypick
        name: Test action
        uses: innerspacetrainings/Cherry-pick-action@main
        with:
          release: release/v1.5.0
          email: dev@innerspace.at
          name: inspdevtools
      - name: something
        run: |
          echo ${{ steps.cherrypick.outputs.create-pr }}
          echo ${{ steps.cherrypick.outputs.branch-name }}
        shell: bash